redis:
  image: redis
  ports:
    - "6379:6379"

db:
  image: mongo:latest #postgres, mysql, mongo. You can also specifiy a specific version instead of using latest.
  ports:
    - "27017:27017" #for postgres "5432:5432", for mysql "3306:3306", for mongo "27017:27017", etc

server:
  #Docker-sails supports several different tags:
  #0.10.32/33/34 (node 0.10.32), stable (latest node 0.10.x), latest (latest node 0.11.x)
  #0.10.32/33/34-pm2 (node 0.10.32), stable-pm2 (latest node 0.10.x), latest-pm2 (latest node 0.11.x)
  image: claudiocro/tektronix-metacatalog
  command: node app.js
  volumes:
    - server/:/server
  ports:
    - "1337:1337"

  links:
    - db
    - redis
  environment:  
  - NODE_ENV=docker
  #For a future version
  #  - VIRTUAL_HOST=sails
  #  - VIRTUAL_PORT=1337
